version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - app
        container_name: dct_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: dct_app

    db:
        image: mariadb:10.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: notSecureChangeMe

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "8877:80"
        environment:
            - PMA_ARBITRARY=1
